package com.orcchg.arkanoid.surface;

public class Levels {  
  public static String[] get(int index) {
    if (index < 0 || index >= TOTAL_LEVELS) {
      index = 0;
    }
    return levels[index];
  }
  
  private static final String[] L0 = new String[] {"          ",
                                                   "          ",
                                                   "          ",
                                                   "          ",
                                                   "  SSSSSS  ",
                                                   "  SSSSSS  ",
                                                   "  SSSSSS  ",
                                                   "  SSSSSS  "};
  
  private static final String[] L1 = new String[]{"          ",
                                                  "          ",
                                                  "          ",
                                                  "          ",
                                                  "  BBBBBB  ",
                                                  "  BSSSSB  ",
                                                  "  BSSSSB  ",
                                                  "  BSSSSB  ",
                                                  "  BSSSSB  ",
                                                  "  BBBBBB  "};
  
  private static final String[] L2 = new String[]{"          ",
                                                  "          ",
                                                  "          ",
                                                  "          ",
                                                  "          ",
                                                  "          ",
                                                  "FFFFFFFFFF",
                                                  "FFFFFFFFFF",
                                                  "FFFFFCFFFF",
                                                  "FFFFCCFFFF",
                                                  "FFFCCCCFFF",
                                                  "FFCCCCCCFF",
                                                  "FCCCCCCCCF",
                                                  "CCCCCCCCCC",
                                                  "BBBBBBBBBB",
                                                  "          "};
  
  private static final String[] L3 = new String[]{"          ",
                                                  "          ",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S",
                                                  "S   TB   S"};
  
  private static final String[] L4 = new String[] {" S    SS  ",
                                                   "S   SS    ",
                                                   " S S      ",
                                                   "  S    SS ",
                                                   "   S  S  S",
                                                   "    BS    ",
                                                   "   SR S   ",
                                                   "  S R  S  ",
                                                   "   SR   S ",
                                                   "    R     ",
                                                   "    R     ",
                                                   "    R   S ",
                                                   "    R SS  ",
                                                   "    RS    ",
                                                   "   RRR    ",
                                                   "   RRR    ",
                                                   " CCCCCCC  ",
                                                   "CCCCCCCCCC"};
  
  private static final String[] L5 = new String[]{"          ",
                                                  "          ",
                                                  "          ",
                                                  "          ",
                                                  "          ",
                                                  "         S",
                                                  "        SB",
                                                  "       SBB",
                                                  "      SBBB",
                                                  "     SBBBB",
                                                  "    SBBBBA",
                                                  "   SBBBBAI",
                                                  "    SBBBBA",
                                                  "     SBBBB",
                                                  "      SBBB",
                                                  "       SBB",
                                                  "        SB",
                                                  "         S"};
  
  private static final String[] L6 = new String[]{"          ",
                                                  "          ",
                                                  "          ",
                                                  "          ",
                                                  "          ",
                                                  "          ",
                                                  "    T     ",
                                                  "   TSB    ",
                                                  "  TSSSB   ",
                                                  " TSSSSSB  ",
                                                  "  TSSSSB  ",
                                                  "   TSSB   ",
                                                  "    TB    ",
                                                  "     B    ",
                                                  "    BST   ",
                                                  "   BSSST  ",
                                                  "  BSSSSST ",
                                                  "   BSSST  ",
                                                  "    BBT   ",
                                                  "     B    "};
  
  private static final String[] L7 = new String[] {"          ",
                                                   "          ",
                                                   "          ",
                                                   "          ",
                                                   "          ",
                                                   "AAAAAAAAAA",
                                                   "AASSSSSSAA",
                                                   "AAAAAASSAA",
                                                   "AASSSSSSAA",
                                                   "AASSAAAAAA",
                                                   "AASSSSSSAA",
                                                   "AAAAAAAAAA",
                                                   "BBBBBBBBBB"};
  
  private static final String[] L8 = new String[] {"          ",
                                                   "          ",
                                                   "          ",
                                                   "          ",
                                                   "WJWWWWWWWJ",
                                                   "WWJWWWWWJW",
                                                   "WWWJWWWJWW",
                                                   "WWWWJWJWWW",
                                                   "WWWWWJWWWW",
                                                   "WWWWJWJWWW",
                                                   "WWWJWWWJWW",
                                                   "WWJWWWWWJW",
                                                   "WJWWWWWWWJ"};
  
  private static final String[] L9 = new String[] {"          ",
                                                   "          ",
                                                   "          ",
                                                   "          ",
                                                   "          ",
                                                   "TTTTTTTTTT",
                                                   "          ",
                                                   " LBBBBBBB ",
                                                   " LBBBBBBB ",
                                                   " LBBBBBBB ",
                                                   " LBBBBBBB ",
                                                   " LBBBBBBB ",
                                                   " LBBBBBBB ",
                                                   "          ",
                                                   "          ",
                                                   "FFFFFFFFFF",
                                                   "FFFFFFFFFF",
                                                   "FFFFFFFFFF",
                                                   "FFFFFFFFFF",
                                                   "SSSSSSSSSS"};
  
  private static final String[] L10 = new String[] {"    TT    ",
                                                    "    II    ",
                                                    "   L  L   ",
                                                    "  L    L  ",
                                                    " T      T ",
                                                    "  TTFFTT  ",
                                                    " FFFFFFFF ",
                                                    " TTFFFFTT ",
                                                    " GGTTTTGG ",
                                                    " RRJJJJRR ",
                                                    "  IIIIII  "};
  
  private static final String[] L11 = new String[] {"FFFIIIIFFF",
                                                    "FFSBBBBSFF",
                                                    "FSBB  BBSF",
                                                    "SBB    BBS",
                                                    "BB      BB",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF",
                                                    "CCCCCCCCCC",
                                                    "CCCCCCCCCC",
                                                    "WWWWWWWWWW",
                                                    "WWWWWWWWWW",
                                                    "WWWWWWWWWW"};
  
  private static final String[] L12 = new String[] {" PP  I    ",
                                                    "P  P  I   ",
                                                    " P  L  P  ",
                                                    "  P  L  P ",
                                                    "P  P  T  P",
                                                    " L  I  P  ",
                                                    "  L  I  P ",
                                                    "   L  I  P",
                                                    "    L  T  ",
                                                    "B  T  T  S",
                                                    " B  T  T S"};
  
  private static final String[] L13 = new String[] {"    LL    ",
                                                    "    LL    ",
                                                    "    LL    ",
                                                    "    LL    ",
                                                    "VGGGLLGGGV",
                                                    "VGGGGGGGGV",
                                                    "VGGGGGGGGV",
                                                    "VGGTTTTGGV",
                                                    "VGGGGGGGGV",
                                                    "VGGGGGGGGV",
                                                    "VGGVVVVGGV",
                                                    "TPPIIIIPPT",
                                                    "T        T"};
  
  private static final String[] L14 = new String[] {"P   U    P",
                                                    "P        P",
                                                    "P        P",
                                                    "P        P",
                                                    "P        P",
                                                    "TT  TTT  P",
                                                    "         P",
                                                    "         P",
                                                    "         P",
                                                    "  TTT   TT",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "TTT   TT  "};
  
  private static final String[] L15 = new String[] {"          ",
                                                    "SS  SSSR S",
                                                    "S S S SRSS",
                                                    "SS  SSSR S",
                                                    "          ",
                                                    "    DD    ",
                                                    "  N TT N  ",
                                                    "  TTKKTT  ",
                                                    "  BBBBBB  ",
                                                    " BBBBBBBB ",
                                                    "BBRRRRRRBB",
                                                    "BRRRJJRRRB",
                                                    "BBBBJJBBBB",
                                                    "BZZJJJJZZB",
                                                    "BZZJJJJZZB",
                                                    "BBJRRRRJBB",
                                                    "BJJBRRBJJB",
                                                    "JJZBBBBZJJ",
                                                    "JJJJBBJJJJ",
                                                    "BBJJRRJJBB",
                                                    "BJJRRRRJJB",
                                                    " BJJBBJJB ",
                                                    " BBBBBBBB ",
                                                    "BBBBBBBBBB",
                                                    "FBBBYYBBBF",
                                                    "FFBBFFBBFF",
                                                    "FFFFFFFFFF",
                                                    "FFFFFFFFFF"};
  
  private static final String[] L16 = new String[] {"          ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "         G",
                                                    "        GG",
                                                    "       GGG",
                                                    "      GGGL",
                                                    "     GGGLL",
                                                    "    GGGLLL",
                                                    "  GGLLLLLL",
                                                    "GGGLLLLLLL",
                                                    "GGGGGLLLLL",
                                                    " GGGGGLLLL",
                                                    "   GGGGGLL",
                                                    "     GGGGL",
                                                    "       GGG",
                                                    "        GG",
                                                    "         G"};
  
  private static final String[] L17 = new String[] {"  SSSSSS  ",
                                                    "  #XSSX#  ",
                                                    "  SSSSSS  ",
                                                    "    SS    ",
                                                    "    SS    ",
                                                    "  SSSSSS  ",
                                                    " SXXXXXXS ",
                                                    " SSESSESS ",
                                                    "  SSSSSS  ",
                                                    "   S  S   ",
                                                    "          ",
                                                    "          ",
                                                    "  #BBBB#  ",                                                    "          ",
                                                    "          ",
                                                    " X   X   X",
                                                    " X   X   X",
                                                    " T   T   T",                                                    "          ",
                                                    " P   P   P",
                                                    " L   L   L",
                                                    " I   I   I",
                                                    " B   B   B",                                                    "          ",
                                                    " S   S   S",
                                                    " K   K   K"};
  
  private static final String[] L18 = new String[] {"XXE    EXX",
                                                    "  P    P  ",
                                                    "  PPPPPP  ",
                                                    "  PPPPPP  ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "    KK    ",
                                                    "  XXXXXX  "};
  
  private static final String[] L19 = new String[] {" BPPPB    ",
                                                    "  BPB     ",
                                                    "   B      ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "      ZZ#D",
                                                    "    ZZD#ZZ",
                                                    "  ZZD#ZZ  "};
  
  private static final String[] L20 = new String[] {"SSSSSSSSES",
                                                    "SSSESSSSSS",
                                                    "SSSSSSSSSS",
                                                    "ESSSSSSSSE",
                                                    "SSSSSSSSSS",
                                                    "SSSSSESSSS",
                                                    "T  R T  RT",
                                                    " TR   TR  ",
                                                    "  T    T  ",
                                                    " R B   BR ",
                                                    "   R   R  "};
  
  private static final String[] L21 = new String[] {"SSSSSDOESS",
                                                    "SSDOESSSSS",
                                                    "SSSSSSDOES",
                                                    "SDOESSSSSS",
                                                    "SESSSSSDOE",
                                                    "SOSSSSSSSS",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "   TTTT   ",
                                                    "          "};
  
  private static final String[] L22 = new String[] {"SSSSSESSSS",
                                                    "SSESSSSSES",
                                                    "JJJJJJJJJJ",
                                                    "JJJJJJJJJJ",
                                                    "PPPPPPPPPP",
                                                    "PPPPPPPKPP",
                                                    "LLLLLLLLLL",
                                                    "LLLLLLLLLL",
                                                    "IIIIKIIIII",
                                                    "IIIIIIIIII",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "SKSSSSSSSS",
                                                    "SSSSSSSSSS"};
  
  private static final String[] L23 = new String[] {"   P      ",
                                                    "          ",
                                                    "   E      ",
                                                    "  XXX     ",
                                                    "         X",
                                                    "        X ",
                                                    "       X  ",
                                                    "      X  $",
                                                    "          "};
  
  private static final String[] L24 = new String[] {"TTTTTTTTPP",
                                                    "        PP",
                                                    "        PP",
                                                    "        PP",
                                                    "         E",
                                                    "  VVVVVXXX"};
  
  private static final String[] L25 = new String[] {"TTTTTTTTTT",
                                                   "  ISSSSSI ",
                                                   "   IAAAI  ",
                                                   "    IAI   ",
                                                   "     B    ",
                                                   "    FF    ",
                                                   "   FFFF   ",
                                                   "  FFFFFF  ",
                                                   "  XFFFFX  ",
                                                   "   XEEX   ",
                                                   "    XX    "};
  
  private static final String[] L26 = new String[] {"          ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBYBBB",
                                                    "BBBBBBBBBB",
                                                    "BBYBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBYBBB",
                                                    "          ",
                                                    "XXXXXXXXXX",
                                                    " Y      Y ",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBBBYBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBYBBBBYBB"};
  
  private static final String[] L27 = new String[] {"          ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "          ",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBMBBBBMBB",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBMBBBBMBB",
                                                    "BBBBBBBBBB",
                                                    "          ",
                                                    "  M    M  ",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "BBBBBBBBBB",
                                                    "  M    M  "};
  
  private static final String[] L28 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L29 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L30 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L31 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L32 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L33 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L34 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L35 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L36 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L37 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L38 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L39 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L40 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L41 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L42 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L43 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L44 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L45 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L46 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L47 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L48 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L49 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L50 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L51 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L52 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L53 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L54 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L55 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L56 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L57 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L58 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L59 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[] L60 = new String[] {"",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    "",
                                                    ""};
  
  private static final String[][] levels = {L0, L1, L2, L3, L4, L5, L6, L7, L8, L9,
                                            L10, L11, L12, L13, L14, L15, L16, L17, L18,
                                            L19, L20, L21, L22, L23, L24, L25, L26, L27,
                                            /*L28, L29, L30, L31, L32, L33, L34, L35, L36,
                                            L37, L38, L39, L40, L41, L42, L43, L44, L45,
                                            L46, L47, L48, L49, L50, L51, L52, L53, L54,
                                            L55, L56, L57, L58, L59, L60*/};
  
  public static final int TOTAL_LEVELS = levels.length;
}
